name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - Assignment2 - Cole Stewart
    paths:
        - "wordle-web/**"
  pull_request:
    branches:
      - Assignment2
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test Job
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 18
      - name: Install Packages
        run: npm ci
        working-directory: ./wordle-web
      - name: Generate
        run: npm run generate
        working-directory: ./wordle-web
      - name: Run Vitest
        run: npm run test
        working-directory: ./wordle-web
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: ./wordle-web/.output/public
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    name: Deploy to Azure
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: ./wordle-web/.output/public
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_PLANT_0D494D21E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./wordle-web/.output/public" # App source code path
          output_location: ".output/public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######